apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.config.proxyPort}}
              protocol: TCP
          env:
            - name: PORT
              value: {{.Values.config.proxyPort | quote}}
            - name: SAML_METADATA_ENDPOINT
              value: {{.Values.config.samlMetadataEndpoint}}
            - name: SAML_HOSTS
              value: {{.Values.config.samlHosts}}
            - name: SAML_ALLOW_IDP_INITIATED
              value: {{.Values.config.samlAllowIdpInitiated | quote}}
            - name: SAML_SIGN_REQUEST
              value: {{.Values.config.samlSignRequest | quote}}
            - name: SSL_CERTIFICATE_PATH
              value: {{.Values.config.sslCertificatePath}}
            - name: SSL_CERTIFICATE_KEY_PATH
              value: {{.Values.config.sslCertificateKeyPath}}
            - name: SSL_CERTIFICATE_AUTOGENERATE
              value: {{.Values.config.sslCertificateAutogenerate | quote}}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
