replicaCount: 1

config:
  # Your Identity provider metadata endpoint
  # https://myidp.com/metadata/000000000000
  samlMetadataEndpoint:
  # List of allowed hosts
  samlHosts: []
  samlAllowIdpInitiated: true
  samlSignRequest: true
  sslCertificateAutogenerate: true
  # No need to specify those if you are auto-generating certificates
  sslCertificatePath: ""
  sslCertificateKeyPath: ""
  proxyPort: 9000
  protocol: https

image:
  repository: public.ecr.aws/f4h3b7s7/saml-proxy
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
