name: Saml proxy image deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_FOR_GITHUB }}
          role-session-name: GitHubActions
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - run: npm install
      - uses: docker/setup-buildx-action@v1
      - name: Run deployment script
        run: node pipeline.js
        env:
          GITHUB_USERNAME: MatteoGioioso
          GITHUB_EMAIL: gioioso.matteo@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: ap-southeast-1
          GITHUB_REPOSITORY_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          ECR_REPOSITORY_URL: public.ecr.aws/hirvitek
          HELM_EXPERIMENTAL_OCI: 1
          ENV: prod
