name: Saml proxy image deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - run: npm install
      - uses: docker/setup-buildx-action@v1
      - name: Run deployment script
        run: GITHUB_REPOSITORY_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" node pipeline.js
        env:
          GITHUB_USERNAME: MatteoGioioso
          GITHUB_EMAIL: gioioso.matteo@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/saml-proxy
          HELM_EXPERIMENTAL_OCI: 1
          ENV: prod
